name: GitHub Actions Demo
on: [push]
env:
  VERSION: 0.0.1
jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password:
            ${{ secrets.CR_PAT }}
      - uses: actions/checkout@v2
      - run: ./build
      - run: docker tag clutroth/dockerpi:latest ghcr.io/clutroth/dockerpi3:latest
      - run: docker tag clutroth/dockerpi:latest ghcr.io/clutroth/dockerpi3:${VERSION}
      - run: docker tag clutroth/dockerpi:vmlatest ghcr.io/clutroth/dockerpi3:vmlatest
      - run: docker tag clutroth/dockerpi:vmlatest ghcr.io/clutroth/dockerpi3:vm${VERSION}
      - run: docker images --format="{{.Repository}}:{{.Tag}}" --filter=reference='ghcr.io/clutroth/dockerpi3:*' | xargs -L 1 docker push
