name: GitHub Actions Demo
on: [push]
jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password:
              ${{ secrets.CR_PAT }}
      - run: docker tag clutroth/dockerpi:latest ghcr.io/clutroth/dockerpi3:latest
      - run: docker tag clutroth/dockerpi:latest ghcr.io/clutroth/dockerpi3:latest
      - run: docker push ghcr.io/clutroth/dockerpi3:latest